ORG_NAME: "Acme Technologies Ltd."
POLICY_OWNER: "Head of Information Security"
INCIDENT_MANAGER: "Security Operations Manager"
LEGAL_CONTACT: "General Counsel"
REVIEW_FREQUENCY: "Annual"
CURRENT_VERSION: "1.0"
EFFECTIVE_DATE: "2025-09-02"
CONTACT_EMAIL: "security@acme.example"
JURISDICTION: "Kenya"
TIMEZONE: "Africa/Nairobi"
PASSWORD_MIN_LENGTH: 14
PASSWORD_ROTATION_DAYS: 365
PASSWORD_REUSE_HISTORY: 24
MFA_REQUIRED: true
PASSWORD_MANAGER_ALLOWED: true
LOCKOUT_THRESHOLD: 10
LOCKOUT_DURATION_MIN: 15
SERVICE_ACCOUNT_ROTATION_DAYS: 90
IR_EXERCISE_FREQUENCY: "Semi-annual"
